### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by maennchen** [ex-security-advisory/api#9]
Think about a good name & Domain for this project.

**Comment by maennchen** [comment]
@greysteil `elixir-security-vulnerability.org` ?

**Comment by greysteil** [comment]
How about `elixiradvisories.com`?

**Comment by maennchen** [comment]
Sounds better I guess. Why `.com` though? It's not really commercial.

**Comment by greysteil** [comment]
Just always what I default to. See it on lots of community projects (e.g., https://keepachangelog.com) but `.org` works too!
